FROM openjdk:8-jre-slim

EXPOSE 8080

RUN mkdir /app

COPY relay-service/build/libs/*.jar /app/relay-service.jar

ENTRYPOINT ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app/relay-service.jar"]