FROM openjdk:8-jre-slim

EXPOSE 8080

RUN mkdir /app

COPY sprint-service/build/libs/*.jar /app/sprint-service.jar

ENTRYPOINT ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app/sprint-service.jar"]